import enum
import uuid
from datetime import UTC, date, datetime

from sqlalchemy import DateTime, Enum, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models.project import Package
from app.models.rate_item import RateSource


class CostSheetStatus(str, enum.Enum):
    DRAFT = "draft"
    VERIFIED = "verified"
    SUPERSEDED = "superseded"
    UNVERIFIED = "unverified"  # auto-generated by a skip (M.2 rule 3) -- not implemented yet


class WorkPackage(str, enum.Enum):
    """Part O COST_SHEETS.lines[].work_package -- 'REQUIRED (NOT NULL) ...
    because contingency grouping (K.1 step 6) depends on it.'"""

    CIVIL = "civil"
    STRUCTURE = "structure"
    FLOORING = "flooring"
    ELECTRICAL = "electrical"
    POOL = "pool"
    HVAC = "hvac"
    ACCESSORIES = "accessories"
    SCOPE = "scope"
    SERVICES = "services"


class EstimateStatus(str, enum.Enum):
    DRAFT = "draft"
    SENT = "sent"
    EXPIRED = "expired"


class EstimateOptionClientStatus(str, enum.Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEMAND_RECEIVED = "demand_received"


class QuotationStatus(str, enum.Enum):
    DRAFT = "draft"
    RELEASED = "released"
    SENT = "sent"
    WON = "won"
    LOST = "lost"
    EXPIRED = "expired"


class CostSheet(Base):
    """Part M.1 stage 1. document_no reuses the project's own YYMM-####
    suffix with a CS- prefix (M.2 rule 10: 'one project number ... is
    shared by its Cost Sheet, Estimate and Quotation'). cost_total can
    still be entered directly (a single whole-project figure, the original
    document-state-machine skeleton's simplification), OR built up from
    real CostSheetLine rows below and then set via POST .../recompute,
    which applies K.1 steps 1, 2, 3 and 6 (material, labour-category-%
    fallback, site establishment % (D.4), contingency by work_package).
    K.1 steps 4-5A (freight/crane, design & approvals, tender/warranty
    overheads, company overhead recovery) are not yet wired into the
    recompute -- still a documented gap."""

    __tablename__ = "cost_sheets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False
    )
    document_no: Mapped[str] = mapped_column(String(30), unique=True, nullable=False)
    revision_major: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    revision_minor: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    status: Mapped[CostSheetStatus] = mapped_column(
        Enum(CostSheetStatus, name="cost_sheet_status"), default=CostSheetStatus.DRAFT, nullable=False
    )
    cost_total: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)

    verified_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    verified_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    created_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False
    )


class CostSheetLine(Base):
    """Part O COST_SHEETS.lines[] -- one take-off quantity line. rate/unit/
    source/city_of_quote are copied onto the line (not a live join to
    RATE_ITEMS) so an already-verified Cost Sheet's figures never drift if
    the master rate sheet changes later (M.2 rule 5's freezing principle,
    applied at line level). rate_item_id is kept only for traceability back
    to where the rate came from. Manually entered for now; Parts D/E/F's
    take-off engine will populate these programmatically from real
    quantities instead."""

    __tablename__ = "cost_sheet_lines"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    cost_sheet_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cost_sheets.id"), nullable=False
    )
    # Site-wide lines (e.g. a shared site-establishment item) have no
    # single sport; per-sport take-off lines (structure, flooring, ...) do.
    project_sport_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project_sports.id"), nullable=True
    )
    rate_item_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("rate_items.id"), nullable=True
    )
    work_package: Mapped[WorkPackage] = mapped_column(
        Enum(WorkPackage, name="work_package"), nullable=False
    )
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    item_name: Mapped[str] = mapped_column(String(200), nullable=False)
    spec: Mapped[str | None] = mapped_column(String(300), nullable=True)
    unit: Mapped[str] = mapped_column(String(20), nullable=False)
    quantity: Mapped[float] = mapped_column(Numeric(14, 3), nullable=False)
    rate: Mapped[float] = mapped_column(Numeric(12, 2), nullable=False)
    source: Mapped[RateSource] = mapped_column(
        Enum(RateSource, name="rate_source"), default=RateSource.MANUAL, nullable=False
    )
    city_of_quote: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # J.2: "the blended 22% is used only when an item has none" -- nullable,
    # not required.
    labour_category_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("labour_categories.id"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False
    )


class Estimate(Base):
    """Part M.1 stage 2. Cannot be created until its Cost Sheet is
    Verified (M.2 rule 1). Status here covers only Draft/Sent/Expired --
    'client approved' is derived from its options (M.4a #7: 'ESTIMATES.
    status is derived: approved if any option approved; rejected only if
    all rejected'), not stored on the Estimate itself."""

    __tablename__ = "estimates"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False
    )
    cost_sheet_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cost_sheets.id"), nullable=False
    )
    document_no: Mapped[str] = mapped_column(String(30), unique=True, nullable=False)
    revision_major: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    revision_minor: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    status: Mapped[EstimateStatus] = mapped_column(
        Enum(EstimateStatus, name="estimate_status"), default=EstimateStatus.DRAFT, nullable=False
    )
    sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    expires_at: Mapped[date | None] = mapped_column(DateTime, nullable=True)

    created_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False
    )


class EstimateOption(Base):
    """One product option (Budget/Standard/Premium) for one sport on an
    Estimate (M.1: 'client-facing budget per sport with product options').
    cost_for_option is PM/Director-entered (Sales never sees it, K.3);
    price_low/price_high are the client-facing, GST-inclusive range at
    +/- 5% around the target-margin selling price (M.1: 'range_pct
    [confirm 5%]', M.6: 'GST-inclusive')."""

    __tablename__ = "estimate_options"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    estimate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("estimates.id"), nullable=False
    )
    project_sport_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("project_sports.id"), nullable=False
    )
    package: Mapped[Package] = mapped_column(Enum(Package, name="package"), nullable=False)

    cost_for_option: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    price_low: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    price_high: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)

    client_status: Mapped[EstimateOptionClientStatus] = mapped_column(
        Enum(EstimateOptionClientStatus, name="estimate_option_client_status"),
        default=EstimateOptionClientStatus.PENDING,
        nullable=False,
    )
    client_demand_note: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False
    )


class Quotation(Base):
    """Part M.1 stage 3. Cannot be created until the Estimate shows
    Client approved or Client demand received on at least one option
    (M.2 rule 2). Covers the approved subset of sports (M.2 rule 11) via
    QuotationLine below. Values are frozen at creation, matching M.2 rule
    5 ('every document freezes its rates ... at approval time') -- this
    skeleton has no later re-pricing step, so creation time is freeze time."""

    __tablename__ = "quotations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False
    )
    estimate_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("estimates.id"), nullable=False
    )
    document_no: Mapped[str] = mapped_column(String(30), unique=True, nullable=False)
    revision_major: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    revision_minor: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    status: Mapped[QuotationStatus] = mapped_column(
        Enum(QuotationStatus, name="quotation_status"), default=QuotationStatus.DRAFT, nullable=False
    )

    cost_total: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    target_margin_percent: Mapped[float] = mapped_column(Numeric(5, 2), nullable=False)
    floor_margin_percent: Mapped[float] = mapped_column(Numeric(5, 2), nullable=False)
    selling_price_ex_gst: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    discount_type: Mapped[str | None] = mapped_column(String(10), nullable=True)
    discount_value: Mapped[float] = mapped_column(Numeric(14, 2), default=0, nullable=False)
    discount_amount: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    selling_after_discount: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    margin_percent: Mapped[float] = mapped_column(Numeric(6, 2), nullable=False)
    below_floor: Mapped[bool] = mapped_column(nullable=False)
    gst_amount: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)
    quotation_total: Mapped[float] = mapped_column(Numeric(14, 2), nullable=False)

    # M.2 rule 3: a Quotation on an Unverified Cost Sheet needs Director
    # release and can't be marked Won until verified. Always False here --
    # Estimate creation already requires a Verified Cost Sheet in this
    # skeleton (skip-stage isn't implemented), kept for when it is.
    cost_basis_unverified: Mapped[bool] = mapped_column(default=False, nullable=False)

    released_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )
    released_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    expires_at: Mapped[date | None] = mapped_column(DateTime, nullable=True)
    won_lost_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_by_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(UTC), nullable=False
    )


class QuotationLine(Base):
    """The approved-subset link (M.2 rule 11: 'the Quotation covers the
    approved subset' of the project's sports) -- one row per EstimateOption
    included in this Quotation."""

    __tablename__ = "quotation_lines"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    quotation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("quotations.id"), nullable=False
    )
    estimate_option_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("estimate_options.id"), nullable=False
    )
