"""add margin_policies table

Revision ID: 03fe8b0edfd1
Revises: 878fd498d268
Create Date: 2026-09-05 08:49:30.692289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '03fe8b0edfd1'
down_revision: Union[str, None] = '878fd498d268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('margin_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_type', postgresql.ENUM('SCHOOL', 'COLLEGE', 'HOUSING_SOCIETY', 'CORPORATE', 'CLUB', 'GOVERNMENT', 'INDIVIDUAL', name='client_type', create_type=False), nullable=False),
    sa.Column('floor_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('competitive_segment', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('margin_policies')
    # ### end Alembic commands ###
