"""add is_active to sports and scope_items

Revision ID: 27b79fd8f9fb
Revises: f7f63bdc39f6
Create Date: 2026-09-07 20:43:15.510656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27b79fd8f9fb'
down_revision: Union[str, None] = 'f7f63bdc39f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing seeded rows as active; dropped
    # after backfill since the ORM column has no server-side default.
    op.add_column('scope_items', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('sports', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('scope_items', 'is_active', server_default=None)
    op.alter_column('sports', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'is_active')
    op.drop_column('scope_items', 'is_active')
    # ### end Alembic commands ###
