"""Add Part M.3: Attachments and approval evidence

Revision ID: 2f50e25c998f
Revises: 65f2f63c0a87
Create Date: 2026-09-07 16:31:30.441586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '2f50e25c998f'
down_revision: Union[str, None] = '65f2f63c0a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_type', postgresql.ENUM('COST_SHEET', 'ESTIMATE', 'QUOTATION', name='override_document_type', create_type=False), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('original_size', sa.Integer(), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('tag', sa.Enum('APPROVAL_EVIDENCE', 'CLIENT_DEMAND', 'GST_OPINION', 'STRUCTURAL_DESIGN', 'SOIL_REPORT', 'SURVEY_FORM', 'VENDOR_QUOTE', 'DRAWING', 'PHOTO', 'PRODUCT_IMAGE', 'SIGNED_DOCUMENT', 'DELIVERY_CHALLAN', 'INVOICE', 'REFERENCE', name='attachment_tag'), nullable=False),
    sa.Column('approval_strength', sa.Enum('FORMAL', 'INFORMAL', name='approval_strength'), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    # ### end Alembic commands ###
