"""add sports and project_sports tables

Revision ID: 30f7326bb5d8
Revises: d2b47f276fec
Create Date: 2026-09-04 20:36:58.815144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '30f7326bb5d8'
down_revision: Union[str, None] = 'd2b47f276fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('INDOOR', 'OUTDOOR', name='sport_category'), nullable=False),
    sa.Column('playing_dims', sa.String(length=200), nullable=False),
    sa.Column('build_dims', sa.String(length=300), nullable=False),
    sa.Column('min_clear_height_ft', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('governing_body', sa.String(length=150), nullable=False),
    sa.Column('source_citation', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('project_sports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sport_id', sa.UUID(), nullable=False),
    sa.Column('building_status', postgresql.ENUM('EXISTING_BUILDING', 'NEW_PEB_BUILDING', 'OPEN_AIR', 'COVERED_SHED', name='building_status', create_type=False), nullable=False),
    sa.Column('number_of_courts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_sports')
    op.drop_table('sports')
    # ### end Alembic commands ###
    # building_status is owned by the earlier projects migration, not dropped
    # here — only sport_category was created by this one.
    sa.Enum(name='sport_category').drop(op.get_bind(), checkfirst=True)
