"""add tender_details table

Revision ID: 33d6979cf581
Revises: 03fe8b0edfd1
Create Date: 2026-09-05 09:17:02.610864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33d6979cf581'
down_revision: Union[str, None] = '03fe8b0edfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('emd_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('emd_validity_date', sa.Date(), nullable=True),
    sa.Column('retention_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('performance_bg_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dlp_months', sa.Integer(), nullable=False),
    sa.Column('bid_due_date', sa.Date(), nullable=True),
    sa.Column('pre_bid_meeting_date', sa.Date(), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_details')
    # ### end Alembic commands ###
