"""add messages table

Revision ID: 347a45338372
Revises: 7e9b695d24bf
Create Date: 2026-09-07 21:23:35.748486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '347a45338372'
down_revision: Union[str, None] = '7e9b695d24bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column(
        'doc_type',
        postgresql.ENUM('COST_SHEET', 'ESTIMATE', 'QUOTATION', name='override_document_type', create_type=False),
        nullable=False,
    ),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WHATSAPP', name='message_channel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_note', sa.String(length=500), nullable=True),
    sa.Column('attachment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RECORDED', 'SENT', 'DELIVERED', 'FAILED', name='message_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
