"""add numeric playing/build dims to sports

Revision ID: 5b8a85531dbf
Revises: 30f7326bb5d8
Create Date: 2026-09-04 21:15:53.074621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b8a85531dbf'
down_revision: Union[str, None] = '30f7326bb5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sports', sa.Column('playing_l_ft', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('sports', sa.Column('playing_w_ft', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('sports', sa.Column('build_l_ft', sa.Numeric(precision=6, scale=1), nullable=True))
    op.add_column('sports', sa.Column('build_w_ft', sa.Numeric(precision=6, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sports', 'build_w_ft')
    op.drop_column('sports', 'build_l_ft')
    op.drop_column('sports', 'playing_w_ft')
    op.drop_column('sports', 'playing_l_ft')
    # ### end Alembic commands ###
