"""Add wastage_percent to CostSheetLine (Part J.3)

Revision ID: 65f2f63c0a87
Revises: a4189a84bf5f
Create Date: 2026-09-07 16:00:33.360379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65f2f63c0a87'
down_revision: Union[str, None] = 'a4189a84bf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_sheet_lines', sa.Column('wastage_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_sheet_lines', 'wastage_percent')
    # ### end Alembic commands ###
