"""add part o vendors and purchase orders

Revision ID: 7e43241cdf3a
Revises: 2f50e25c998f
Create Date: 2026-09-07 18:20:23.948025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e43241cdf3a'
down_revision: Union[str, None] = '2f50e25c998f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('rcm_applicable', sa.Boolean(), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_no', sa.String(length=30), nullable=False),
    sa.Column('cost_sheet_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='purchase_order_status'), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('eway_bill_no', sa.String(length=30), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_sheet_id'], ['cost_sheets.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_no')
    )
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('cost_sheet_line_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['cost_sheet_line_id'], ['cost_sheet_lines.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_order_lines')
    op.drop_table('purchase_orders')
    op.drop_table('vendors')
    # ### end Alembic commands ###
