"""add rate_history table and rate_items.is_commodity_watched

Revision ID: 7e9b695d24bf
Revises: 27b79fd8f9fb
Create Date: 2026-09-07 21:05:54.015477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e9b695d24bf'
down_revision: Union[str, None] = '27b79fd8f9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_item_id', sa.UUID(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['rate_item_id'], ['rate_items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default backfills existing rate items as not-watched;
    # dropped after backfill since the ORM column has no server-side default.
    op.add_column(
        'rate_items', sa.Column('is_commodity_watched', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('rate_items', 'is_commodity_watched', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_items', 'is_commodity_watched')
    op.drop_table('rate_history')
    # ### end Alembic commands ###
