"""add labour_categories and rate_items tables

Revision ID: 878fd498d268
Revises: aabf7cdbfb61
Create Date: 2026-09-04 21:32:52.737232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '878fd498d268'
down_revision: Union[str, None] = 'aabf7cdbfb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labour_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('rate_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('hsn_sac', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.Enum('AI', 'MANUAL', name='rate_source'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('vendor', sa.String(length=150), nullable=True),
    sa.Column('confirmed_date', sa.Date(), nullable=True),
    sa.Column('city_of_quote', sa.String(length=100), nullable=True),
    sa.Column('labour_category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['labour_category_id'], ['labour_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_items')
    op.drop_table('labour_categories')
    # ### end Alembic commands ###
