"""Add CostSheetLine (Parts D-J take-off foundation)

Revision ID: a4189a84bf5f
Revises: 7f5cf0b1bf4d
Create Date: 2026-09-06 19:44:47.582018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'a4189a84bf5f'
down_revision: Union[str, None] = '7f5cf0b1bf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_sheet_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cost_sheet_id', sa.UUID(), nullable=False),
    sa.Column('project_sport_id', sa.UUID(), nullable=True),
    sa.Column('rate_item_id', sa.UUID(), nullable=True),
    sa.Column('work_package', sa.Enum('CIVIL', 'STRUCTURE', 'FLOORING', 'ELECTRICAL', 'POOL', 'HVAC', 'ACCESSORIES', 'SCOPE', 'SERVICES', name='work_package'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.String(length=300), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', postgresql.ENUM('AI', 'MANUAL', name='rate_source', create_type=False), nullable=False),
    sa.Column('city_of_quote', sa.String(length=100), nullable=True),
    sa.Column('labour_category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_sheet_id'], ['cost_sheets.id'], ),
    sa.ForeignKeyConstraint(['labour_category_id'], ['labour_categories.id'], ),
    sa.ForeignKeyConstraint(['project_sport_id'], ['project_sports.id'], ),
    sa.ForeignKeyConstraint(['rate_item_id'], ['rate_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_sheet_lines')
    # ### end Alembic commands ###
