"""add scope_items and project_scope_items tables

Revision ID: aabf7cdbfb61
Revises: 5b8a85531dbf
Create Date: 2026-09-04 21:24:52.970214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aabf7cdbfb61'
down_revision: Union[str, None] = '5b8a85531dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scope_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('group', sa.Enum('CIVIL', 'ELECTRICAL', 'WATER', 'EXTERNAL', 'SERVICES', 'MAINTENANCE', name='scope_item_group'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('project_scope_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scope_item_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_scope_items')
    op.drop_table('scope_items')
    # ### end Alembic commands ###
