"""add settings and overrides tables

Revision ID: b2dbda2d6daf
Revises: b479250dfbbf
Create Date: 2026-09-06 12:07:29.737052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2dbda2d6daf'
down_revision: Union[str, None] = 'b479250dfbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('COST_SHEET', 'ESTIMATE', 'QUOTATION', name='override_document_type'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('master_value', sa.String(length=200), nullable=False),
    sa.Column('override_value', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'CITY', 'CLIENT_TYPE', 'SPORT', 'PACKAGE', name='setting_scope'), nullable=False),
    sa.Column('scope_value', sa.String(length=100), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('overrides')
    # ### end Alembic commands ###
