"""add cost_sheets, estimates, estimate_options, quotations, quotation_lines tables

Revision ID: b479250dfbbf
Revises: 33d6979cf581
Create Date: 2026-09-05 09:37:41.019702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b479250dfbbf'
down_revision: Union[str, None] = '33d6979cf581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_no', sa.String(length=30), nullable=False),
    sa.Column('revision_major', sa.Integer(), nullable=False),
    sa.Column('revision_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VERIFIED', 'SUPERSEDED', 'UNVERIFIED', name='cost_sheet_status'), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_no')
    )
    op.create_table('estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cost_sheet_id', sa.UUID(), nullable=False),
    sa.Column('document_no', sa.String(length=30), nullable=False),
    sa.Column('revision_major', sa.Integer(), nullable=False),
    sa.Column('revision_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'EXPIRED', name='estimate_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cost_sheet_id'], ['cost_sheets.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_no')
    )
    op.create_table('estimate_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estimate_id', sa.UUID(), nullable=False),
    sa.Column('project_sport_id', sa.UUID(), nullable=False),
    sa.Column('package', postgresql.ENUM('BUDGET', 'STANDARD', 'PREMIUM', name='package', create_type=False), nullable=False),
    sa.Column('cost_for_option', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_low', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('price_high', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('client_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DEMAND_RECEIVED', name='estimate_option_client_status'), nullable=False),
    sa.Column('client_demand_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['project_sport_id'], ['project_sports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('estimate_id', sa.UUID(), nullable=False),
    sa.Column('document_no', sa.String(length=30), nullable=False),
    sa.Column('revision_major', sa.Integer(), nullable=False),
    sa.Column('revision_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'SENT', 'WON', 'LOST', 'EXPIRED', name='quotation_status'), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('floor_margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('selling_price_ex_gst', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('selling_after_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('below_floor', sa.Boolean(), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quotation_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis_unverified', sa.Boolean(), nullable=False),
    sa.Column('released_by_id', sa.UUID(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('won_lost_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_no')
    )
    op.create_table('quotation_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('estimate_option_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_option_id'], ['estimate_options.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_lines')
    op.drop_table('quotations')
    op.drop_table('estimate_options')
    op.drop_table('estimates')
    op.drop_table('cost_sheets')
    # ### end Alembic commands ###
