"""add clients, projects, regional multipliers

Revision ID: d2b47f276fec
Revises: 7fe901169b21
Create Date: 2026-09-04 20:18:24.264577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd2b47f276fec'
down_revision: Union[str, None] = '7fe901169b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('SCHOOL', 'COLLEGE', 'HOUSING_SOCIETY', 'CORPORATE', 'CLUB', 'GOVERNMENT', 'INDIVIDUAL', name='client_type'), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('overdue_flag', sa.Boolean(), nullable=False),
    sa.Column('blacklist_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regional_multipliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('labour_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('transport_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('material_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('climate_zone', sa.String(length=50), nullable=False),
    sa.Column('rainfall_zone', sa.String(length=50), nullable=False),
    sa.Column('coastal', sa.Boolean(), nullable=False),
    sa.Column('wind_zone', sa.String(length=50), nullable=False),
    sa.Column('seismic_zone', sa.String(length=50), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_no', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('site_address', sa.String(length=500), nullable=True),
    sa.Column('site_state_code', sa.String(length=10), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('site_condition', sa.Enum('LEVEL', 'SLOPED', 'WATER_LOGGED', name='site_condition'), nullable=False),
    sa.Column('soil_type', sa.Enum('NORMAL', 'ROCKY', 'BLACK_COTTON', 'SANDY', 'FILLED', name='soil_type'), nullable=False),
    sa.Column('building_status', sa.Enum('EXISTING_BUILDING', 'NEW_PEB_BUILDING', 'OPEN_AIR', 'COVERED_SHED', name='building_status'), nullable=False),
    sa.Column('site_access', sa.Enum('GOOD', 'NARROW_ROAD', 'NO_CRANE_ACCESS', name='site_access'), nullable=False),
    sa.Column('power_available', sa.Enum('YES', 'NO', 'PARTIAL', name='power_available'), nullable=False),
    sa.Column('water_available', sa.Boolean(), nullable=False),
    sa.Column('number_of_courts', sa.Integer(), nullable=False),
    sa.Column('unit_system', sa.Enum('FEET', 'METRES', name='unit_system'), nullable=False),
    sa.Column('package', sa.Enum('BUDGET', 'STANDARD', 'PREMIUM', name='package'), nullable=False),
    sa.Column('safe_bearing_capacity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('existing_building_clear_height_ft', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tender_mode', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('regional_multipliers')
    op.drop_table('clients')
    # ### end Alembic commands ###
