"""add client_signatories and attachment signatory fields

Revision ID: f7f63bdc39f6
Revises: 7e43241cdf3a
Create Date: 2026-09-07 20:29:47.925945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7f63bdc39f6'
down_revision: Union[str, None] = '7e43241cdf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_signatories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('authorization_date', sa.Date(), nullable=False),
    sa.Column('authorization_doc_attachment_id', sa.UUID(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorization_doc_attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attachments', sa.Column('signatory_name', sa.String(length=200), nullable=True))
    op.add_column('attachments', sa.Column('signatory_designation', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'signatory_designation')
    op.drop_column('attachments', 'signatory_name')
    op.drop_table('client_signatories')
    # ### end Alembic commands ###
