import { useEffect, useState } from "react";
import { getRolePermissions } from "./api";

// Amendment 51 (Section 55): the Director's "who can do what" view, generated by
// the backend from the very role checks it enforces (GET /role-permissions) --
// it replaced a hand-kept mirror (rolePermissionsData.js) that had drifted from
// the code. Still view-only: a role's access changes only when the code does.
const ROLE_LABELS = {
  sales: "Sales",
  pm: "PM",
  director: "Director",
  procurement: "Procurement",
  site_engineer: "Site Engineer",
  ca_tax: "CA / Tax",
};

// Prose about behaviour, not a role list, so it is not derivable from the route
// table and stays as written.
const SAFETY_CRITICAL_RULES = [
  {
    name: "K.3 — Cost & margin hidden from Sales",
    detail:
      "\"Cost, contingency, markup and margin are never visible to Sales or Procurement — enforced at the API, not just hidden in the browser.\" Sales sees a Rate-blind Cost Sheet with cost fields stripped, never the real figure. Procurement sees item/qty/rate on exports, never an aggregate cost or margin.",
  },
  {
    name: "M.2 — Director-only quotation lifecycle gates",
    detail:
      "An Estimate can't be created until its Cost Sheet is Verified. Sales can request a stage skip but can't approve one alone (rule 3). Editing a Verified/Sent document creates a new revision and blocks re-release until rebased (rule 4). Rejecting a client status requires a reason (rule 9).",
  },
  {
    name: "Director-count guardrail",
    detail:
      "A Director can't deactivate their own account, and can't deactivate or demote the last active Director — User Management is itself Director-only, so hitting zero active Directors would make the app unrecoverable without a raw database script.",
  },
];

const UNGATED_HEADINGS = {
  any_signed_in: "Any signed-in user",
  public: "No sign-in needed",
};

// "message-templates" -> "Message templates"
function areaTitle(area) {
  const words = area.replace(/[-_]/g, " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function RouteLine({ item }) {
  return (
    <li className="break-words">
      {item.label}{" "}
      <span className="text-[10px] text-text-secondary/70 font-mono break-all">
        {item.method} {item.path}
      </span>
    </li>
  );
}

export default function RolePermissionsViewer({ token }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [selectedRole, setSelectedRole] = useState(null); // null = show everything

  useEffect(() => {
    getRolePermissions(token)
      .then(setData)
      .catch((err) => setError(err.message));
  }, [token]);

  if (error) return <p className="text-sm text-red-400">{error}</p>;
  if (!data) return <p className="text-sm text-text-secondary">Loading…</p>;

  return (
    <div className="space-y-4">
      <div>
        <h3 className="text-sm font-semibold text-text-secondary mb-1">Roles &amp; permissions</h3>
        <p className="text-xs text-text-secondary">
          What each role can do, read live from the access checks the server enforces ({data.gated_route_count}{" "}
          role-gated actions across {data.areas.length} areas) — so it cannot fall out of date. View-only: a role&apos;s
          access changes only when the underlying code changes.
        </p>
      </div>

      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => setSelectedRole(null)}
          className={`text-xs rounded px-3 py-1.5 border ${
            selectedRole === null
              ? "bg-gold text-base border-gold font-semibold"
              : "border-border-dark text-text-secondary hover:text-text-primary"
          }`}
        >
          All roles
        </button>
        {data.roles.map((role) => (
          <button
            key={role}
            onClick={() => setSelectedRole(role)}
            className={`text-xs rounded px-3 py-1.5 border ${
              selectedRole === role
                ? "bg-gold text-base border-gold font-semibold"
                : "border-border-dark text-text-secondary hover:text-text-primary"
            }`}
          >
            {ROLE_LABELS[role] || role}
          </button>
        ))}
      </div>

      <div className="space-y-3">
        {data.areas.map((area) => {
          const groups = selectedRole ? area.groups.filter((g) => g.roles.includes(selectedRole)) : area.groups;
          if (groups.length === 0) return null;
          return (
            <div key={area.area} className="border border-border-dark rounded px-4 py-3">
              <h4 className="text-sm font-semibold text-text-primary mb-2">{areaTitle(area.area)}</h4>
              <div className="space-y-2">
                {groups.map((g) => (
                  <div key={g.roles.join(",")} className="text-xs">
                    <div className="flex flex-wrap gap-1 mb-1">
                      {g.roles.map((r) => (
                        <span
                          key={r}
                          className={`rounded px-1.5 py-0.5 ${
                            r === selectedRole ? "bg-gold text-base font-semibold" : "bg-surface-raised text-text-secondary"
                          }`}
                        >
                          {ROLE_LABELS[r] || r}
                        </span>
                      ))}
                    </div>
                    <ul className="list-disc list-inside text-text-secondary space-y-0.5">
                      {g.items.map((item) => (
                        <RouteLine key={`${item.method} ${item.path}`} item={item} />
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          );
        })}

        {data.ungated.length > 0 && (
          <div className="border border-border-dark rounded px-4 py-3">
            <h4 className="text-sm font-semibold text-text-primary mb-2">Open to every role</h4>
            <div className="space-y-2">
              {Object.keys(UNGATED_HEADINGS).map((access) => {
                const items = data.ungated.filter((u) => u.access === access);
                if (items.length === 0) return null;
                return (
                  <div key={access} className="text-xs">
                    <p className="text-text-secondary mb-1">{UNGATED_HEADINGS[access]}</p>
                    <ul className="list-disc list-inside text-text-secondary space-y-0.5">
                      {items.map((item) => (
                        <RouteLine key={`${item.method} ${item.path}`} item={item} />
                      ))}
                    </ul>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      <div className="border border-gold/40 rounded px-4 py-3 bg-gold-muted">
        <h4 className="text-sm font-semibold text-gold mb-2">Safety-critical rules — not adjustable</h4>
        <p className="text-xs text-text-secondary mb-3">
          These stay hardcoded regardless of role, by design — this is exactly why this screen is a viewer and not an
          editor.
        </p>
        <div className="space-y-3">
          {SAFETY_CRITICAL_RULES.map((rule) => (
            <div key={rule.name}>
              <p className="text-xs font-semibold text-text-primary">{rule.name}</p>
              <p className="text-xs text-text-secondary mt-0.5">{rule.detail}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
